{
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ               ‘ซฎข เ์ : rus_GALDICT " ซ ชโจช  9.1"                   บ
 บ     โ  แฎงค ญจ๏ 29/10/24                                             บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
}

{$ifdef __MTtabledef__}
{อออออออออออออ ’ กซจๆ  : SNG_PREMIYA::SPVEDDEP "SPVEDDEP" ออออออออออออออ}
type
  pSPVEDDEP = ^tSPVEDDEP;
  tSPVEDDEP = record   { - SPVEDDEP }
    CLSCH          : Comp;            { CLSCH                                 }
    SUMUD          : Double;          { SUMUD                                 }
    DFORM          : Date;            { DFORM                                 }
  end;
const
  tiSPVEDDEP01           = 0;  { CLSCH(M)                                }

const
  mtSPVEDDEP = 'SNG_PREMIYA::SPVEDDEP';
{$endif __MTtabledef__}
